# Generated by Django 5.2.7 on 2026-07-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeOfArt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timeExecutionDays", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ArtTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sonOf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artwork.arttags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("tags", models.ManyToManyField(blank=True, to="artwork.arttags")),
                (
                    "typeofArt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artwork.typeofart",
                    ),
                ),
            ],
        ),
    ]
