# Generated by Django 5.2.7 on 2026-08-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artwork", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "type_of_art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artwork.typeofart",
                    ),
                ),
            ],
        ),
    ]
